# Generated by Django 5.2 on 2025-04-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_skills_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='description',
        ),
    ]
