# Generated by Django 5.2 on 2025-04-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_skills_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
